I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 291, in script
    f "Are you mark?"
Exception: Sayer 'f' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 291, in script
    f "Are you mark?"
  File "C:\Users\Student01\Desktop\renpy-7.1.1-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Student01\Desktop\renpy-7.1.1-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'f' is not defined.

Windows-7-6.1.7601-SP1
Ren'Py 7.1.1.929
Marble 1.0
Fri Nov 02 15:17:16 2018
